### ISSUE TITLE
2024 EDU SIG Chair 选举提名

### ISSUE THREAD

**Issue by sunny0826** [lfapac-open-source-evangelist/education-and-talent-development-sig#10]
按照 [SIG 章程](https://github.com/lfapac-open-source-evangelist/education-and-talent-development-sig/blob/main/CHARTER.md)，2024年 EDU SIG 主席将由 SIG 成员选举产生。主席的任期为一年，由每年 4月1日 至下一年 3月31日，可连任。

SIG 主席需要是 LFAPAC 开源布道者成員之一，本次拥有提名权的成员为：@sunny0826 @wzshiming @zRich @hintcnuie @huayk @rockpanda @tao12345666333 @pacoxu @isLinXu @gzchenyong @Nliver

以上成员可以在本 Issue 中直接 comment 进行提名，提名格式为：

```md
- 姓名：<被提名人的姓名>
- 介绍：<被提名人的个人介绍以及对 EDU SIG 的贡献等>
```

时间线：

~3月1日 - 3月10日：确定投票权以及提名权~
3月11日-3月17日：提名主席
3月18日-3月26日：投票
3月27日-3月31日：结果公示（我們会在3月27日晚的例会會上公布結果，对结果有异议可在例会中提出讨论）
4月1日：正式生效

**Comment by sunny0826** [comment]
- 姓名：郭旭东
- 介绍：2022\2023 连续两年担任 EDU SIG Chair，曾代表 EDU SIG 在 GOTC 和国际开源节（IOSF）上发言并获得LFOSSA 2022/2023年度开源推广大使和LFOSSA 2022年度开源明星奖，协助 LFOSSA 完成开源教育 SIG 年度报告（半年一次），建立 LFAPAC 布道者团队视频账号，剪辑并发布了 10 期 KubeCon China 2023 的布道者访谈视频。

**Comment by tao12345666333** [comment]
- 姓名：郭旭东
- 介绍：2022\2023 连续两年担任 EDU SIG Chair，在各类会议/活动中都在积极进行开源教育布道，非常活跃

**Comment by huayk** [comment]
姓名：郭旭东
介绍：2022\2023 连续两年担任 EDU SIG Chair，在各类会议/活动中积极分享各种资料内容和经验。

**Comment by sunny0826** [comment]
@huayk @tao12345666333 感谢认可，不过已经被提名候选人就不要重复提名了，在相关提名后点 👍 即可

**Comment by sunny0826** [comment]
提名截止
