### ISSUE TITLE
2024 EDU SIG 主席投票

### ISSUE THREAD

**Issue by sunny0826** [lfapac-open-source-evangelist/education-and-talent-development-sig#12]
按照 [SIG 章程](https://github.com/lfapac-open-source-evangelist/education-and-talent-development-sig/blob/main/CHARTER.md)，2024年 EDU SIG 主席将由 SIG 成员选举产生。主席的任期为一年，由每年 4月1日 至下一年 3月31日，可连任。

SIG 主席需要是 LFAPAC 开源布道者成員之一，本次拥有投票权的成员为：@sunny0826 @wzshiming @zRich @hintcnuie @huayk @rockpanda @tao12345666333 @pacoxu @isLinXu @gzchenyong @Nliver

投票方式：由于本次主席选举只有 郭旭东@sunny0826 一名候选人被提名，故在本 issue 下 comment +1 即可

如有其他意见，可以直接 comment 提出即可，我们会与您取得联系

时间线：

~3月1日 - 3月10日：确定投票权以及提名权~
~3月11日-3月17日：提名主席~
3月18日-3月26日：投票
3月27日-3月31日：结果公示（我們会在3月27日晚的例会會上公布結果，对结果有异议可在例会中提出讨论）
4月1日：正式生效

**Comment by windsonsea** [comment]
+1

**Comment by tao12345666333** [comment]
+1

**Comment by ErikJiang** [comment]
+1

**Comment by huayk** [comment]
+1

**Comment by zRich** [comment]
+1

**Comment by wzshiming** [comment]
+1
