### ISSUE TITLE
[New Member]王嘉树

### ISSUE THREAD

**Issue by wjsvec** [lfapac-open-source-evangelist/education-and-talent-development-sig#2]
### Self Introduction(自我介绍)

我是王嘉树，北京邮电大学研三在读的学生，校园的业余布道师，对开源文化很感兴趣。开源之夏第一位开源大使，开放原子校园大使，这是我的一些和开源教育相关的活动：
 - CommunityOverCode (原 ApacheCon) 上《开源之夏最佳实践》的演讲：https://www.bagevent.com/event/cocasia-2023
![image](https://github.com/lfapac-open-source-evangelist/education-and-talent-development-sig/assets/39830125/f415dea7-f2e9-4e44-ae62-4fd51db1dca4)

 - 《开源之夏最佳实践》同名文档项目https://github.com/opensource-f2f/ospp-best-practice
![image](https://github.com/lfapac-open-source-evangelist/education-and-talent-development-sig/assets/39830125/2d878586-7fff-494e-bbcf-e1405f506409)

 - 开放原子峰会上北邮校园行代表的演讲
 
![image](https://github.com/lfapac-open-source-evangelist/education-and-talent-development-sig/assets/39830125/fccfb20c-f394-454f-b1e5-e6e13287e037)

- 微信号: wjsvector

**Comment by wjsvec** [comment]
申请加入Education 特别兴趣小组 （SIG）

**Comment by sunny0826** [comment]
欢迎加入！
