### ISSUE TITLE
[New Member] J6ChenXiang

### ISSUE THREAD

**Issue by J6ChenXiang** [lfapac-open-source-evangelist/education-and-talent-development-sig#3]
### Self Introduction(自我介绍)

在华为从事计算机软件开发5.8年，先后接触过低软信令协议解析，终端android linux fwk 优化和定制开发，华为高斯数据库开发。
主要技术栈为C/C++, Rust, Java。

在进行开源CVE漏洞修补过程中，接触到LFAPAC，希望能加入其中学习和为开源贡献自己的力量。

- 微信号: 

微信号：chenxiang6716

**Comment by sunny0826** [comment]
@J6ChenXiang 已添加微信，请通过一下

**Comment by sunny0826** [comment]
已邀请进群
