### ISSUE TITLE
[New Member] 华永奎

### ISSUE THREAD

**Issue by huayk** [lfapac-open-source-evangelist/education-and-talent-development-sig#4]
### Self Introduction(自我介绍)

大家好：
       我是东软集团华永奎，目前是一名架构师，从事交通行业软件开发，目前参与了很多大型软件架构设计工作，比较了解云平台、大数据平台、云原生平台，熟悉各种软件架构，擅长湖仓一体化架构。喜欢各种前沿技术，如大语言模型等。很早就加入LFAPAC 译道师 SIG群了，跟着各位老师学习新技术。
       在2024年争取参加更多的社区活动。
微信号: gic

**Comment by sunny0826** [comment]
@huayk 您好，您的微信号搜索不到，请检查您提供的微信号是否正确
<img width="239" alt="image" src="https://github.com/lfapac-open-source-evangelist/education-and-talent-development-sig/assets/24563928/7b387ebf-ee49-4a48-ba63-2bbdd430fb32">

**Comment by huayk** [comment]
微信号：13504930918

**Comment by sunny0826** [comment]
已邀请加入微信群
