### ISSUE TITLE
[New Member]: 张晶(Alex Zhang)

### ISSUE THREAD

**Issue by ILoveAmy** [lfapac-open-source-evangelist/education-and-talent-development-sig#6]
### Name(姓名)

张晶

### Self Introduction(自我介绍)

英特尔中国区AI开发者布道策略经理；《深度学习图像识别技术》《Python语言程序设计》作者之一；LabVIEW注册构架师；上海交通大学创新学院企业导师；东莞理工学院企业硕士导师；EdgeX Foundry社区布道师。

### 微信号

18675388132

### 公司

英特尔(中国)有限公司

**Comment by sunny0826** [comment]
已邀请
