### ISSUE TITLE
2024 EDU SIG Chair 选举投票权确认

### ISSUE THREAD

**Issue by sunny0826** [lfapac-open-source-evangelist/education-and-talent-development-sig#7]
按照 [SIG 章程](https://github.com/lfapac-open-source-evangelist/education-and-talent-development-sig/blob/main/CHARTER.md)，2024年 EDU SIG 主席将由 SIG 成员选举产生。主席的任期为一年，由每年 4月1日 至下一年 3月31日，可连任。

SIG 主席需要是 LFAPAC 开源布道者成員之一，本 [SIG member](https://github.com/lfapac-open-source-evangelist/education-and-talent-development-sig/blob/main/CHARTER.md#%E5%A6%82%E4%BD%95%E6%88%90%E4%B8%BA-member) 可享有投票权以及提名权。

如果你是 SIG 成员并愿意参与投票，通过在本 issue 下 +1 即可。因为本次为首次开放 SIG 成员的投票权，故只需在本 Issue +1 即认为您是 EDU SIG 成员，同时请提交 PR 在 [README#members](https://github.com/lfapac-open-source-evangelist/education-and-talent-development-sig/tree/main?tab=readme-ov-file#members) 中确认您的成员身份（如果您还没有提交过 PR，请参考：[本文档](https://github.com/firstcontributions/first-contributions/blob/main/translations/README.zh-cn.md)）。我在投票权确定、本 issue 关闭后，开启提名流程。

时间线：

现在 - 3月10日：确定投票权以及提名权
3月11日-3月17日：提名主席
3月18日-3月26日：投票
3月27日-3月31日：结果公示（我們会在3月27日晚的例会會上公布結果，对结果有异议可在例会中提出讨论）
4月1日：正式生效

**Comment by sunny0826** [comment]
+1

**Comment by gzchenyong** [comment]
+1

**Comment by isLinXu** [comment]
+1

**Comment by pacoxu** [comment]
+1

**Comment by tao12345666333** [comment]
+1

**Comment by rockpanda** [comment]
+1

**Comment by huayk** [comment]
+1

**Comment by hintcnuie** [comment]
+1

**Comment by zRich** [comment]
+1

**Comment by hintcnuie** [comment]
+1

**Comment by sunny0826** [comment]
投票权已确认，拥有本次投票权和提名权的成员为 @sunny0826 @wzshiming @zRich @hintcnuie @huayk @rockpanda @tao12345666333 @pacoxu @isLinXu @gzchenyong @Nliver
